pipeline {
    agent { label 'new-node' }
    triggers {
        githubPush()
    }
    stages {
        stage('Git Clone') {
            steps {
                git url: 'https://github.com/harshada137/Python_Projects.git', branch: 'main'
                echo 'Clonning Repo'
            }
        }
      
      stage('Execute Repo') {
            steps {
                sh '''
                 'echo "myfile.txt" | python3 Word Count Tool/main.py'
                '''
              
            }
        }
    }
}
